
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/cmake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/cmake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/Embarcadero/Studio/23.0/bin/bcc32.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Embarcadero C++ 7.70 for Win32 Copyright (c) 1993-2023 Embarcadero Technologies, Inc.
      CMakeCXXCompilerId.cpp:
      Turbo Incremental Link 6.97 Copyright (c) 1997-2022 Embarcadero Technologies, Inc.
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.tds"
      
      The CXX compiler identification is Embarcadero, found in:
        D:/hwinfo/CMakeFiles/3.30.2/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/cmake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/hwinfo/CMakeFiles/CMakeScratch/TryCompile-bhcauo"
      binary: "D:/hwinfo/CMakeFiles/CMakeScratch/TryCompile-bhcauo"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "-tM"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "-tM -lS:1048576 -lSc:4098 -lH:1048576 -lHc:8192"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/hwinfo/CMakeFiles/CMakeScratch/TryCompile-bhcauo'
        
        Run Build Command(s): C:/cmake/bin/cmake.exe -E env VERBOSE=1 make -f Makefile cmTC_43dfa\\fast
        MAKE Version 5.43  Copyright (c) 1987, 2019 Embarcadero Technologies, Inc.
        	make  -f CMakeFiles\\cmTC_43dfa.dir\\build.make -l -o  CMakeFiles\\cmTC_43dfa.dir\\build
        MAKE Version 5.43  Copyright (c) 1987, 2019 Embarcadero Technologies, Inc.
        Building CXX object CMakeFiles/cmTC_43dfa.dir/CMakeCXXCompilerABI.cpp.obj
        	D:\\Embarcadero\\Studio\\23.0\\bin\\bcc32.exe -tR -DWIN32   -tM -Od -v -oCMakeFiles\\cmTC_43dfa.dir\\CMakeCXXCompilerABI.cpp.obj -P -c C:\\cmake\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp
        Embarcadero C++ 7.70 for Win32 Copyright (c) 1993-2023 Embarcadero Technologies, Inc.
        C:\\cmake\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp:
        Linking CXX executable cmTC_43dfa.exe
        	D:\\Embarcadero\\Studio\\23.0\\bin\\bcc32.exe -tR -ecmTC_43dfa.exe -tM -lS:1048576 -lSc:4098 -lH:1048576 -lHc:8192 -v -tC -tM -Od -v @MAKE0000.@@@
        Embarcadero C++ 7.70 for Win32 Copyright (c) 1993-2023 Embarcadero Technologies, Inc.
        Turbo Incremental Link 6.97 Copyright (c) 1997-2022 Embarcadero Technologies, Inc.
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/cmake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
